name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        compiler: [gcc, clang++]
    
    runs-on: ubuntu-latest
    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt install gcc
        sudo apt install clang
      
    - name: Check environment
      run: |
        gcc --version
        clang++ --version
        cmake --version
        make --version
        
    - name: Make build directory
      run: cmake -E make_directory build
      
    - name: CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=$CXX
      
    - name: Make
      shell: bash
      run: make -C build
