name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Make build directory
      run: cmake -E make_directory build
      
    - name: CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Make
      shell: bash
      run: "make -C build -j $(nproc)"
