name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        compiler: [gcc-9, clang-10]
    
    runs-on: ubuntu-latest
    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install gcc-9
        sudo apt install clang-10
      
    - name: Check environment
      run: |
        gcc-9 --version
        clang-10 --version
        cmake --version
        make --version
        
    - name: Make build directory
      run: cmake -E make_directory build
      
    - name: CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=$CXX
      
    - name: Make
      shell: bash
      run: make -C build
