name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        compiler: [g++-10, clang++-10]
    
    runs-on: ubuntu-latest
    env:
      CXX: ${{matrix.compiler}}

    steps:
    - uses: actions/checkout@v2
      
    - name: Check environment
      run: |
        g++-10 --version
        clang++-10 --version
        cmake --version
        make --version
        
    - name: Make build directory
      run: cmake -E make_directory build
      
    - name: CMake
      env:
        CXXFLAGS: -Wall -Wpedantic -Wextra -Werror
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=$CXX
      
    - name: Make
      shell: bash
      run: make -C build
      
    - name: Test
      run: build/test/voxelio-test
