name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        compiler: [g++, clang++]
        build_type: [Debug, Release]
    
    runs-on: ubuntu-latest
    env:
      CXX: ${{matrix.compiler}}

    steps:
    - uses: actions/checkout@v2
      
    - name: Check environment
      run: |
        g++ --version
        clang++ --version
        $CXX --version
        cmake --version
        make --version
      
    - name: CMake
      env:
        CXXFLAGS: -Wall -Wpedantic -Wextra -Werror
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=$CXX
      
    - name: Build
      shell: bash
      run: cmake --build build
      
    - name: Test
      run: build/test/voxelio-test
