name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
      
    - name: Make build directory
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmake -E make_directory build
      
    - name: CMake
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=$CXX

    - name: MSBuild
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd build
        msbuild ALL_BUILD.vcxproj
